### ISSUE TITLE
Commands for admin to unshare existing shared folders 

### ISSUE THREAD

**Issue by watermint** [watermint/toolbox#562]

**Comment by RobertHild** [comment]
Is it possible with these commands for an **administrator** to 
- unshare all files and folders of a user
- delete all shared links, upload links and transfer links
- "leave" all shares that this user received from others

Looking forward to your reply, kind regards,
Robert

**Comment by watermint** [comment]
Hi.
Here is the command description that is for shared link control for members.
https://toolbox.watermint.org/guides/dropbox-business.html#team-shared-link-commands

And, here is the table for commands that available run as a member.
There is no command available to "leave" shared folder now. I'll file that as an separate issue.

Command | Description
-- | --
team runas file batch copy | Batch copy files/folders as a member
team runas file sync batch up | Batch sync up that run as members
team runas sharedfolder batch share | Batch share folders for members
team runas sharedfolder batch unshare | Batch unshare folders for members
team runas sharedfolder member batch add | Batch add members to member’s shared folders
team runas sharedfolder member batch delete | Batch delete members from member’s shared folders

**Comment by RobertHild** [comment]
Hi @watermint,

sorry for bothering you again with this issue - but I still need some clarification on these commands and parameters.

Which is the command that I can run as a team **administrator** in order to unshare files and folders of a user / member?
Can I run '_team runas sharedfolder batch unshare_' in order to unshare files and folders of this user?

Will the command also work for subfolders and files within the folder when specifying the path in the CSV file?
Or will I need a complete list containing the paths to all files and folders that shall be unshared?

Are there any additional parameters that could be used?

Looking forward to your reply, kind regards,
Robert

**Comment by watermint** [comment]
@RobertHild 
Hi, sorry for the confusion.
Here is the manual for the command `team runas sharedfolder batch unshare`.
https://toolbox.watermint.org/commands/team-runas-sharedfolder-batch-unshare.html

This command requires list of user and folder pairs like below.
```
member_email,path
john@example.com,/projects/my_project
```

If you need to list shared folders of member, here is the command.
https://toolbox.watermint.org/commands/team-namespace-file-list.html

The report format and the input of unshare is bit different. Please use the column `namespace_member_email` and `path_display` of the report to create the input data.
