### ISSUE TITLE
Quick start guide has outdated business_info command

### ISSUE THREAD

**Issue by thelpurcell** [watermint/toolbox#589]
**Describe the bug**
In https://github.com/watermint/toolbox/wiki/Quick-Start-Guide-for-Dropbox-Business-Admins page, under the 'Connecting and running your first Watermint command' section there is a test command called 'business_info' referenced which has now been replaced with 'team info' command. Is it possible to update this document and the associated screenshot for step 1 and step 5?

**To Reproduce**
1. Run command '...' with option '...'
2. See error

**Expected behavior**

**Screenshots, or log snippets**
If applicable, add screenshots or log snippets to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - toolbox Version [e.g. 64.4.220]

**Additional context**

**Comment by watermint** [comment]
I'll deprecate Wiki documentation (because all docs are out of date). Replacing those docs by [Discussions](https://github.com/watermint/toolbox/discussions) and [public facing released documents](https://toolbox.watermint.org)

See also: deprecating Wiki
https://github.com/watermint/toolbox/discussions/672
