### ISSUE TITLE
request for new auth code when sharefolder share command and sharefolder add command

### ISSUE THREAD

**Issue by joshuascottpaul** [watermint/toolbox#666]
**Describe the bug**
request for new auth code when sharefolder share command and sharefolder add command

**To Reproduce**
1. Run command list files command with -auth-database /Users/jpaul/.toolbox/secrets.db
2. goto auth url
3. paste auth code
4. list files works
5. run list files with command with -auth-database /Users/jpaul/.toolbox/secrets.db
6. works fine
7. run sharefolder share with -auth-database /Users/jpaul/.toolbox/secrets.db command ERROR asks to goto auth url again
8. run sharefolder add with -auth-database /Users/jpaul/.toolbox/secrets.db command ERROR asks to goto auth url again

**Expected behavior**
performands command using -auth-database /Users/jpaul/.toolbox/secrets.db and does NOT ask for auth url

**Screenshots, or log snippets**
$ tbx file list -path /neocode -auth-database /Users/jpaul/.toolbox/secrets.db

watermint toolbox 112.8.787
===========================

© 2016-2022 Takayuki Okazaki
Licensed under open source licenses. Use the `license` command for more detail.

Testing network connection...
Done

1. Visit the URL for the auth dialogue:

https://www.dropbox.com/oauth2/authorize?client_id=pbytd54hk4tuwvq&code_challenge=NdobZkkLE7dO_w5tY8X9HQzg_qr8-hL41fhs0VjBZeE&code_challenge_method=S256&response_type=code&scope=account_info.read+files.content.read&state=GMUF2EV7&token_access_type=offline

**Desktop (please complete the following information):**
 - OS: Mac OS 13.0
 - watermint toolbox 112.8.787

**Comment by watermint** [comment]
Hi @joshuascottpaul . Thank you for the request.
Are you still see goto auth url if you run step 7 or step 8 again? (after paste auth code for step 7 & 8)

By default, tbx will ask you an authentication when you request the new auth scope to proceed.
This is because the scope of authorization is intentionally limited to minimize risk.
For example, listing file and updating sharing info requires different scope.

Once you finished authentication for the scope, `tbx` will read auth data from the database instead of asking you for an auth code.

If you don't want to authenticate for multiple type of commands, here is the option.
`-experiment dbx_auth_course_grained_scope`

Run the command like:
```
$ tbx file list -path /neocode -auth-database /Users/jpaul/.toolbox/secrets.db -experiment dbx_auth_course_grained_scope
```

This option will ask you for an authorization of everything the app can do to your Dropbox.

**Comment by joshuascottpaul** [comment]
1 it keeps asking for auth each time - even though i already provided auth code

2 i add the "-experiment dbx_auth_course_grained_scope" but then auth url doesn't work - i don't get the "ALLOW" screeen - instead i get the login screen - even though i am logged in - and trying to login just reloads page.

3 to make "-experiment dbx_auth_course_grained_scope" work do i need to make change to dropbox account? or do i need dropbox pro?

without -experiment dbx_auth_course_grained_scope - normal:
![SCR-20221031-pp0](https://user-images.githubusercontent.com/597763/199139357-63e2904b-59ca-4612-8a5b-d52d83e5779e.png)

with -experiment dbx_auth_course_grained_scope - never logs in
![SCR-20221031-ppe](https://user-images.githubusercontent.com/597763/199139360-7740fef7-f1c7-4856-9ecc-d2123d78b7b3.png)

**Comment by joshuascottpaul** [comment]
this my error - i realize now have to "train" the secrets.db first - by running all commands manually to build up secrets.db.

**Comment by watermint** [comment]
Thanks for comments. Closing this. Please reopen if you have additional question.
